import { lazy, Suspense } from 'react'
import { Block, Prose, SyntheticNote } from '../components/Bits.tsx'

/**
 * The real sensor (`T038`) in its own chunk. It carries the signer and the
 * key store, and the first screen's budget (`SC-013`) is the policy screen's;
 * the chunk is fetched when this tab opens, before anyone can tap Send, so
 * it is not inside `SC-009`'s five seconds either.
 */
const ThisPhone = lazy(() => import('../sensor/ThisPhone.tsx'))

/**
 * Screen 2 — the operator's side. A neighbour with a phone is a sensor too.
 *
 * Everything on it is this phone's own (`T040`): its key and readings, what
 * the aggregator made of them, its stake and earnings on chain, the sensors
 * of its cell. What is not real is said precisely at the foot, not as a
 * blanket line over numbers that are.
 */
const SensorScreen = () => (
  <div>
    <Suspense
      fallback={
        <Block top={0}>
          <Prose>Opening this phone’s sensor key…</Prose>
        </Block>
      }
    >
      <ThisPhone />
    </Suspense>

    <SyntheticNote>
      Rainfall here is typed in by hand from a gauge, or generated by a scenario run — it is not a
      certified measurement. The stake and earnings are mock USDC, a devnet test token: no real
      money moves. The keys, signatures, stake and transfers are real, on Solana devnet.
    </SyntheticNote>
  </div>
)

export default SensorScreen
