import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { largestMinority, minorityFlipsDay, minorityReach } from './minority-shift.ts'

/**
 * `SC-003` measured on real gauges — `fixtures/sc003-gauges.json`, CoCoRaHS on
 * the Front Range, April–September 2025, regenerated by
 * `scripts/sc003-gauges.mjs`. Each cell-day with a quorum of single-day values
 * is one interval; the attacker is the largest minority of its votes, taking
 * the votes it likes and reporting the edge of the column.
 *
 * The numbers are pinned, not budgeted: no budget for the share of flipped days
 * has been set. A change here means the median or the attack changed, and the
 * milestone table has to change with it.
 */

type Gauges = {
  quorum: number
  cells: { cell: string; gauges: { id: string; values: (number | null)[] }[] }[]
}

const fixture: Gauges = JSON.parse(
  readFileSync(new URL('../../../fixtures/sc003-gauges.json', import.meta.url), 'utf8'),
)

/** The pool's dry-day threshold on devnet and in every scenario: 1.0 mm. */
const POOL_DRY_THRESHOLD_X100 = 100

function cellDays() {
  const out: { votes: number[]; reach: NonNullable<ReturnType<typeof minorityReach>> }[] = []
  for (const { gauges } of fixture.cells) {
    const days = gauges[0]?.values.length ?? 0
    for (let day = 0; day < days; day += 1) {
      const votes = gauges
        .map((gauge) => gauge.values[day])
        .filter((value): value is number => value !== null && value !== undefined)
      if (votes.length < fixture.quorum) continue
      const reach = minorityReach(votes, largestMinority(votes.length))
      if (reach === null) throw new Error('a quorum of votes has a value')
      out.push({ votes, reach })
    }
  }
  return out
}

describe('SC-003 on real gauges', () => {
  const days = cellDays()

  it('has the control set the spec asks for, and more', () => {
    expect(fixture.cells).toHaveLength(40)
    expect(days.length).toBe(4_163)
    expect(days.length).toBeGreaterThanOrEqual(200)
    // Witness that the set is not all dry zeros, where nothing can move.
    expect(days.filter(({ reach }) => reach.honestX100 > POOL_DRY_THRESHOLD_X100).length).toBe(
      1_070,
    )
  })

  it('never lets a minority take the value outside the honest gauges', () => {
    const outside = days.filter(
      ({ votes, reach }) =>
        reach.downX100 < Math.min(...votes) || reach.upX100 > Math.max(...votes),
    )
    expect(outside).toEqual([])
  })

  it('flips the day class where the honest gauges straddle the threshold — measured, no budget', () => {
    const flipped = days.filter(({ reach }) => minorityFlipsDay(reach, POOL_DRY_THRESHOLD_X100))
    expect(flipped.length).toBe(283)
    // Every flip is a day the honest gauges themselves disagree about.
    for (const { votes } of flipped) {
      expect(Math.min(...votes) <= POOL_DRY_THRESHOLD_X100).toBe(true)
      expect(Math.max(...votes) > POOL_DRY_THRESHOLD_X100).toBe(true)
    }
  })
})
