// Drives the two-chapter demo against a deployed API and measures what it
// managed — step 0½ of docs/DEPLOY.md, and the instrument `T069` needed.
//
// Run:
//   node scripts/devnet-show.mjs [--api <url>] [--nonce 7] [--payout 1000]
//                                [--spell 14] [--window-days 90] [--no-policy]
//
// Why a script and not three curl commands. The runbook already said chapter
// two has to start "the moment chapter one says done, from code and not by
// hand", and then gave commands for hands. The reason is arithmetic: a
// compressed day is two seconds, so every second of hesitation between the
// chapters is half a day of the policy's window, and a devnet attempt on
// 2026-09-23 started chapter two on day 96 of a window that ended on 94. A
// policy whose window runs out is not merely a failed attempt either — its
// reserve is locked under it for good, because `closeAfterDays` wants every
// day of the window in the database and `BACKLOG_DAYS` does not reach back
// that far.
//
// What it measures. `POST /v1/scenario/run` answers 202 and plays in the
// background, so the rate is not in the answer — it is the slope of
// `published + refused` over `GET /v1/scenario/run/:id`. Sampling it once a
// second gives both the rate and the thing the rate decides: whether the run
// is still where the compressed clock says it should be. A run that falls
// behind does not fail; it publishes into days the aggregator has already
// closed, the cell ends up with no coverage, and the policy the show is about
// pays nothing for reasons no error message mentions.
//
// The genesis it anchors to is read off the pool, not off this machine, and
// both chapters get the identical value. `scenarioStart` derives each
// chapter's day offset from it, so a second chapter with a different genesis
// lands on days the first one already wrote.

import { spawn } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'
import {
  Connection,
  decodePool,
  Keypair,
  PROGRAM_ID,
  PublicKey,
  poolPda,
} from '../packages/anchor-client/src/index.ts'

const ENV_PATH = new URL('../.env', import.meta.url)
const SCENARIOS = new URL('../fixtures/scenarios/', import.meta.url)

/** Between samples of the run. A compressed day is two seconds. */
const POLL_MS = 1_000

/* -------------------------------------------------------------------------- */
/* Arguments                                                                  */
/* -------------------------------------------------------------------------- */

const { values: args } = parseArgs({
  options: {
    api: { type: 'string' },
    /** Chapters, in order. Both are played against the same pool genesis. */
    chapters: { type: 'string', default: 'normal,drought' },
    nonce: { type: 'string', default: '7' },
    payout: { type: 'string', default: '1000' },
    spell: { type: 'string', default: '14' },
    'window-days': { type: 'string', default: '90' },
    /** Plays the chapters and buys nothing — a measurement without a policy. */
    'no-policy': { type: 'boolean', default: false },
  },
})

const chapters = args.chapters.split(',').map((name) => name.trim()).filter((name) => name !== '')
if (chapters.length === 0) {
  console.error('--chapters named nothing to play')
  process.exit(1)
}

/* -------------------------------------------------------------------------- */
/* .env                                                                       */
/* -------------------------------------------------------------------------- */

function env() {
  const found = {}
  for (const line of readFileSync(ENV_PATH, 'utf8').split(/\r?\n/)) {
    const match = line.match(/^([A-Z_]+)=(.*)$/)
    if (match !== null) found[match[1]] = match[2].trim()
  }
  return found
}

function required(values, name, hint) {
  const value = values[name]
  if (value === undefined || value === '') {
    console.error(`${name} is missing from .env — ${hint}`)
    process.exit(1)
  }
  return value
}

const values = env()
const apiBase = (args.api ?? values.VITE_API_URL ?? '').replace(/\/+$/, '')
if (apiBase === '') {
  console.error('no API to drive — pass --api https://… or set VITE_API_URL in .env')
  process.exit(1)
}
const rpcUrl =
  values.SOLANA_RPC_URL === undefined || values.SOLANA_RPC_URL === ''
    ? 'https://api.devnet.solana.com'
    : values.SOLANA_RPC_URL
const programId =
  values.PUMPKING_PROGRAM_ID === undefined || values.PUMPKING_PROGRAM_ID === ''
    ? PROGRAM_ID
    : new PublicKey(values.PUMPKING_PROGRAM_ID)

// One vote per operator (`FR-009`), and the column they land in is where
// rewards and burnt stake settle — so these are keys we hold, generated by
// devnet-keys.mjs, not addresses invented for the request body.
const operators = {}
for (const [label, name] of [
  ['operator-a', 'OPERATOR_A_KEYPAIR'],
  ['operator-b', 'OPERATOR_B_KEYPAIR'],
  ['operator-c', 'OPERATOR_C_KEYPAIR'],
]) {
  const secret = required(values, name, 'run: node scripts/devnet-keys.mjs')
  operators[label] = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(secret))).publicKey.toBase58()
}

/* -------------------------------------------------------------------------- */
/* What the fixtures ask of the deployment                                    */
/* -------------------------------------------------------------------------- */

function scenarioFile(name) {
  return JSON.parse(readFileSync(new URL(`${name}.json`, SCENARIOS), 'utf8'))
}

const first = scenarioFile(chapters[0])
/** `FR-049`: intervals × sensors on one compressed day. 36 on the fixtures. */
const requiredRate =
  (first.clock.intervalsPerDay * first.sensors.length) / first.clock.secondsPerDay

/* -------------------------------------------------------------------------- */
/* The API                                                                    */
/* -------------------------------------------------------------------------- */

async function api(path, init) {
  const response = await fetch(`${apiBase}${path}`, init)
  const text = await response.text()
  let body
  try {
    body = JSON.parse(text)
  } catch {
    body = { error: text.slice(0, 200) }
  }
  return { status: response.status, ok: response.ok, body }
}

const health = await api('/health')
if (!health.ok) {
  console.error(`the API did not answer /health: ${health.status}`)
  process.exit(1)
}
if (health.body.scenarioMode !== true) {
  console.error('SCENARIO_MODE is off on this deployment, so /v1/scenario answers 404.')
  console.error('Turn it on in the platform dashboard, wait for the restart, and run this again.')
  process.exit(1)
}
console.log('api            :', apiBase)
console.log('worker cycles  :', health.body.worker?.cycles ?? '(the loop is elsewhere)')

/* -------------------------------------------------------------------------- */
/* The pool's clock                                                           */
/* -------------------------------------------------------------------------- */

const connection = new Connection(rpcUrl, 'confirmed')
const poolInfo = await connection.getAccountInfo(poolPda(programId).address)
if (poolInfo === null) {
  console.error('the pool is not on this cluster — run scripts/devnet-init.mjs first')
  process.exit(1)
}
const pool = decodePool(Uint8Array.from(poolInfo.data))
const poolGenesis = Number(pool.genesisTs.toString())
const secondsPerDay = pool.secondsPerDay

if (secondsPerDay !== first.clock.secondsPerDay) {
  console.error(
    `the pool runs ${secondsPerDay}s days and ${chapters[0]}.json runs ${first.clock.secondsPerDay}s ones.`,
  )
  console.error('A scenario day would be cut across two chain days and every transition would')
  console.error('cost an extra wet one. Re-initialise the pool, or play a fixture that matches.')
  process.exit(1)
}

// The chain's clock, not this machine's: at two seconds a day a few seconds of
// drift is a few days.
const slot = await connection.getSlot('confirmed')
const blockTime = await connection.getBlockTime(slot)
const chainNow = blockTime === null ? Math.floor(Date.now() / 1_000) : blockTime

// The last day boundary at or before now. Aligning to the grid is what keeps a
// scenario day inside one chain day; a genesis in the future would make every
// reading a measurement from ahead of its own arrival, which `FR-004` files as
// late.
const elapsedDays = Math.max(0, Math.floor((chainNow - poolGenesis) / secondsPerDay))
const anchorTs = new Date((poolGenesis + elapsedDays * secondsPerDay) * 1_000).toISOString()

console.log('pool genesis   :', new Date(poolGenesis * 1_000).toISOString(), `(${secondsPerDay}s days)`)
console.log('chain today    :', elapsedDays)
console.log('run anchored at:', anchorTs)
console.log('chapters       :', chapters.join(' → '))
console.log('rate the clock asks for:', `${requiredRate}/s`)
console.log('')

/* -------------------------------------------------------------------------- */
/* The policy, bought while chapter one plays                                 */
/* -------------------------------------------------------------------------- */

let policyChild = null
if (!args['no-policy']) {
  policyChild = spawn(
    process.execPath,
    [
      fileURLToPath(new URL('devnet-issue.mjs', import.meta.url)),
      '--payout',
      args.payout,
      '--spell',
      args.spell,
      '--window-days',
      args['window-days'],
      '--nonce',
      args.nonce,
    ],
    { stdio: ['ignore', 'inherit', 'inherit'] },
  )
  policyChild.on('error', (cause) => {
    console.error('the policy script would not start:', cause.message)
  })
}

/* -------------------------------------------------------------------------- */
/* Playing a chapter, and watching the slope                                  */
/* -------------------------------------------------------------------------- */

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

/**
 * Plays one chapter to its end, sampling once a second.
 *
 * The rate is the slope of what the intake accepted, and the lag is the same
 * number said the other way: how many readings behind the compressed clock the
 * run is. Both are printed live, because the decision they inform — stop, or
 * let it finish — cannot wait for a summary.
 */
async function play(name) {
  const started = await api('/v1/scenario/run', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ scenario: name, operators, genesisTs: anchorTs }),
  })
  if (started.status !== 202) {
    console.error(`${name}: the run was refused with ${started.status}`)
    console.error(JSON.stringify(started.body, null, 2))
    return null
  }

  const run = started.body
  console.log(
    `${name}: run ${run.run}, ${run.total} readings over ${run.durationSeconds}s,`,
    `day ${run.firstDay} of the pool, due from ${run.startedAt}`,
  )

  const dueAt = new Date(run.startedAt).getTime()
  const samples = []
  let previous = { at: Date.now(), done: 0 }
  let last = run

  for (;;) {
    await sleep(POLL_MS)
    const polled = await api(`/v1/scenario/run/${run.run}`)
    if (!polled.ok) {
      console.error(`${name}: the run stopped answering: ${polled.status}`)
      return null
    }
    last = polled.body
    const now = Date.now()
    const done = last.published + last.refused
    const rate = ((done - previous.done) * 1_000) / Math.max(1, now - previous.at)
    // Where the compressed clock says the run should be by now.
    const due = Math.min(
      last.total,
      Math.max(0, Math.round(((now - dueAt) / 1_000 / run.durationSeconds) * last.total)),
    )
    samples.push({ at: now, done, rate, behind: due - done })
    process.stdout.write(
      `\r  ${name}: ${done}/${last.total}  ${rate.toFixed(1)}/s  behind ${Math.max(0, due - done)}  refused ${last.refused}   `,
    )
    previous = { at: now, done }
    if (last.status !== 'running') break
  }
  process.stdout.write('\n')

  const moving = samples.filter((sample) => sample.rate > 0)
  const rates = moving.map((sample) => sample.rate).sort((a, b) => a - b)
  const wall =
    moving.length < 2
      ? 0
      : (moving[moving.length - 1].at - moving[0].at) / 1_000 +
        (moving.length > 0 ? POLL_MS / 1_000 : 0)
  const overall = wall === 0 ? 0 : (last.published + last.refused) / wall

  console.log(`  status   : ${last.status}${last.error === null ? '' : ` — ${last.error}`}`)
  console.log(`  published: ${last.published}   refused: ${last.refused}   of ${last.total}`)
  console.log(
    `  rate     : ${overall.toFixed(1)}/s overall,`,
    `median ${rates.length === 0 ? 0 : rates[Math.floor(rates.length / 2)].toFixed(1)}/s,`,
    `needed ${requiredRate}/s`,
  )
  console.log(
    `  clock    : ${wall.toFixed(1)}s of wall time for ${run.durationSeconds}s of compressed time`,
  )
  console.log(`  worst lag: ${Math.max(0, ...samples.map((sample) => sample.behind))} readings`)
  return { ...last, overall, wall, requiredRate }
}

/* -------------------------------------------------------------------------- */
/* The show                                                                   */
/* -------------------------------------------------------------------------- */

const played = []
for (const name of chapters) {
  const result = await play(name)
  if (result === null) {
    if (policyChild !== null) policyChild.kill()
    process.exit(1)
  }
  played.push({ name, ...result })
  if (result.status !== 'done') {
    console.error(`${name} did not finish; the chapters after it are not played.`)
    if (policyChild !== null) policyChild.kill()
    process.exit(1)
  }
  // Nothing between the chapters on purpose. Every second here is half a day
  // of the policy's window.
}

console.log('')
console.log('chapter     published  refused  rate/s  needed  wall/compressed')
for (const chapter of played) {
  console.log(
    `  ${chapter.name.padEnd(10)}${String(chapter.published).padStart(9)}`,
    `${String(chapter.refused).padStart(8)}`,
    `${chapter.overall.toFixed(1).padStart(7)}`,
    `${String(chapter.requiredRate).padStart(7)}`,
    `${chapter.wall.toFixed(1)}s / ${chapter.durationSeconds}s`,
  )
}

const slowest = Math.min(...played.map((chapter) => chapter.overall))
if (slowest < requiredRate) {
  console.log('')
  console.log(`The run did not keep up: ${slowest.toFixed(1)}/s against ${requiredRate}/s.`)
  console.log('Days closed while their readings were still being published, so the cell has')
  console.log('less coverage than the fixture describes and the policy may pay nothing.')
}

// The policy script gives up on its own timeout, so this only waits for it —
// and only if it is still running. Attaching to `exit` on a child that has
// already left is a promise nobody will ever settle.
if (policyChild !== null && policyChild.exitCode === null && !policyChild.killed) {
  await new Promise((resolve) => {
    policyChild.on('exit', resolve)
  })
}
